export const FETCH_ALL_BREEDS = 'FETCH_ALL_BREEDS';
export const PICK_10_BREEDS = 'PICK_10_BREEDS';
export const GET_BREED_IMAGES = 'GET_BREED_IMAGES';
export const GET_4_OPTIONS = 'GET_4_OPTIONS';
export const INCREASE_QUIZ_STEP = 'INCREASE_QUIZ_STEP';
export const INCREASE_QUIZ_SCORE = 'INCREASE_QUIZ_SCORE';
export const SET_USER_SELECTED_BREED = 'SET_USER_SELECTED_BREED';